export const mokedDeckList = [
  {
    id: '1701217624256',
    cards: [
      {
        id: 'pl2-88',
        name: "Aaron's Collection",
        supertype: 'Trainer',
        rules: [
          'You can play only one Supporter card each turn. When you play this card, put it next to your Active Pokémon. When your turn ends, discard this card.',
          'Search your discard pile for up to 2 in any combination of Pokémon SP and basic Energy cards, show them to your opponent, and put them into your hand.',
        ],
        set: {
          id: 'pl2',
          name: 'Rising Rivals',
          series: 'Platinum',
          printedTotal: 111,
          total: 120,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'RR',
          releaseDate: '2009/05/16',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/pl2/symbol.png',
            logo: 'https://images.pokemontcg.io/pl2/logo.png',
          },
        },
        number: '88',
        images: {
          small: 'https://images.pokemontcg.io/pl2/88.png',
          large: 'https://images.pokemontcg.io/pl2/88_hires.png',
        },
      },
      {
        id: 'xy4-117',
        name: 'AZ',
        supertype: 'Trainer',
        rules: [
          'Put 1 Pokémon into your hand. (Discard all cards attached to that Pokémon.)',
          'You may play only 1 Supporter card during your turn (before your attack).',
        ],
        set: {
          id: 'xy4',
          name: 'Phantom Forces',
          series: 'XY',
          printedTotal: 119,
          total: 124,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PHF',
          releaseDate: '2014/11/05',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xy4/symbol.png',
            logo: 'https://images.pokemontcg.io/xy4/logo.png',
          },
        },
        number: '117',
        images: {
          small: 'https://images.pokemontcg.io/xy4/117.png',
          large: 'https://images.pokemontcg.io/xy4/117_hires.png',
        },
      },
      {
        id: 'xy4-91',
        name: 'AZ',
        supertype: 'Trainer',
        rules: [
          'Put 1 Pokémon into your hand. (Discard all cards attached to that Pokémon.)',
          'You may play only 1 Supporter card during your turn (before your attack).',
        ],
        set: {
          id: 'xy4',
          name: 'Phantom Forces',
          series: 'XY',
          printedTotal: 119,
          total: 124,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PHF',
          releaseDate: '2014/11/05',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xy4/symbol.png',
            logo: 'https://images.pokemontcg.io/xy4/logo.png',
          },
        },
        number: '91',
        images: {
          small: 'https://images.pokemontcg.io/xy4/91.png',
          large: 'https://images.pokemontcg.io/xy4/91_hires.png',
        },
      },
      {
        id: 'dp2-19',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'dp2',
          name: 'Mysterious Treasures',
          series: 'Diamond & Pearl',
          printedTotal: 123,
          total: 124,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'MT',
          releaseDate: '2007/08/01',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/dp2/symbol.png',
            logo: 'https://images.pokemontcg.io/dp2/logo.png',
          },
        },
        number: '19',
        images: {
          small: 'https://images.pokemontcg.io/dp2/19.png',
          large: 'https://images.pokemontcg.io/dp2/19_hires.png',
        },
      },
      {
        id: 'bw10-26',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Water'],
        set: {
          id: 'bw10',
          name: 'Plasma Blast',
          series: 'Black & White',
          printedTotal: 101,
          total: 105,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PLB',
          releaseDate: '2013/08/14',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw10/symbol.png',
            logo: 'https://images.pokemontcg.io/bw10/logo.png',
          },
        },
        number: '26',
        images: {
          small: 'https://images.pokemontcg.io/bw10/26.png',
          large: 'https://images.pokemontcg.io/bw10/26_hires.png',
        },
      },
      {
        id: 'sm11-42',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Water'],
        set: {
          id: 'sm11',
          name: 'Unified Minds',
          series: 'Sun & Moon',
          printedTotal: 236,
          total: 260,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'UNM',
          releaseDate: '2019/08/02',
          updatedAt: '2021/09/01 05:37:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sm11/symbol.png',
            logo: 'https://images.pokemontcg.io/sm11/logo.png',
          },
        },
        number: '42',
        images: {
          small: 'https://images.pokemontcg.io/sm11/42.png',
          large: 'https://images.pokemontcg.io/sm11/42_hires.png',
        },
      },
      {
        id: 'sm5-38',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Water'],
        set: {
          id: 'sm5',
          name: 'Ultra Prism',
          series: 'Sun & Moon',
          printedTotal: 156,
          total: 178,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'UPR',
          releaseDate: '2018/02/02',
          updatedAt: '2019/02/19 23:25:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sm5/symbol.png',
            logo: 'https://images.pokemontcg.io/sm5/logo.png',
          },
        },
        number: '38',
        images: {
          small: 'https://images.pokemontcg.io/sm5/38.png',
          large: 'https://images.pokemontcg.io/sm5/38_hires.png',
        },
      },
      {
        id: 'ex12-15',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'ex12',
          name: 'Legend Maker',
          series: 'EX',
          printedTotal: 92,
          total: 93,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'LM',
          releaseDate: '2006/02/01',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/ex12/symbol.png',
            logo: 'https://images.pokemontcg.io/ex12/logo.png',
          },
        },
        number: '15',
        images: {
          small: 'https://images.pokemontcg.io/ex12/15.png',
          large: 'https://images.pokemontcg.io/ex12/15_hires.png',
        },
      },
      {
        id: 'base5-49',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'base5',
          name: 'Team Rocket',
          series: 'Base',
          printedTotal: 82,
          total: 83,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'TR',
          releaseDate: '2000/04/24',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/base5/symbol.png',
            logo: 'https://images.pokemontcg.io/base5/logo.png',
          },
        },
        number: '49',
        images: {
          small: 'https://images.pokemontcg.io/base5/49.png',
          large: 'https://images.pokemontcg.io/base5/49_hires.png',
        },
      },
      {
        id: 'ecard1-93',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'ecard1',
          name: 'Expedition Base Set',
          series: 'E-Card',
          printedTotal: 165,
          total: 165,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'EX',
          releaseDate: '2002/09/15',
          updatedAt: '2022/10/10 15:12:00',
          images: {
            symbol: 'https://images.pokemontcg.io/ecard1/symbol.png',
            logo: 'https://images.pokemontcg.io/ecard1/logo.png',
          },
        },
        number: '93',
        images: {
          small: 'https://images.pokemontcg.io/ecard1/93.png',
          large: 'https://images.pokemontcg.io/ecard1/93_hires.png',
        },
      },
      {
        id: 'sv3pt5-63',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'sv3pt5',
          name: '151',
          series: 'Scarlet & Violet',
          printedTotal: 165,
          total: 207,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          releaseDate: '2023/09/22',
          updatedAt: '2023/09/22 15:00:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sv3pt5/symbol.png',
            logo: 'https://images.pokemontcg.io/sv3pt5/logo.png',
          },
        },
        number: '63',
        images: {
          small: 'https://images.pokemontcg.io/sv3pt5/63.png',
          large: 'https://images.pokemontcg.io/sv3pt5/63_hires.png',
        },
      },
      {
        id: 'dp2-69',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'dp2',
          name: 'Mysterious Treasures',
          series: 'Diamond & Pearl',
          printedTotal: 123,
          total: 124,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'MT',
          releaseDate: '2007/08/01',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/dp2/symbol.png',
            logo: 'https://images.pokemontcg.io/dp2/logo.png',
          },
        },
        number: '69',
        images: {
          small: 'https://images.pokemontcg.io/dp2/69.png',
          large: 'https://images.pokemontcg.io/dp2/69_hires.png',
        },
      },
      {
        id: 'xyp-XY178',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'xyp',
          name: 'XY Black Star Promos',
          series: 'XY',
          printedTotal: 211,
          total: 216,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PR-XY',
          releaseDate: '2013/10/12',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xyp/symbol.png',
            logo: 'https://images.pokemontcg.io/xyp/logo.png',
          },
        },
        number: 'XY178',
        images: {
          small: 'https://images.pokemontcg.io/xyp/XY178.png',
          large: 'https://images.pokemontcg.io/xyp/XY178_hires.png',
        },
      },
      {
        id: 'swsh35-38',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'swsh35',
          name: "Champion's Path",
          series: 'Sword & Shield',
          printedTotal: 73,
          total: 80,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'CPA',
          releaseDate: '2020/09/25',
          updatedAt: '2020/10/25 13:45:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh35/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh35/logo.png',
          },
        },
        number: '38',
        images: {
          small: 'https://images.pokemontcg.io/swsh35/38.png',
          large: 'https://images.pokemontcg.io/swsh35/38_hires.png',
        },
      },
      {
        id: 'bw9-67',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'bw9',
          name: 'Plasma Freeze',
          series: 'Black & White',
          printedTotal: 116,
          total: 122,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PLF',
          releaseDate: '2013/05/08',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw9/symbol.png',
            logo: 'https://images.pokemontcg.io/bw9/logo.png',
          },
        },
        number: '67',
        images: {
          small: 'https://images.pokemontcg.io/bw9/67.png',
          large: 'https://images.pokemontcg.io/bw9/67_hires.png',
        },
      },
      {
        id: 'sm4-9',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'sm4',
          name: 'Crimson Invasion',
          series: 'Sun & Moon',
          printedTotal: 111,
          total: 126,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'CIN',
          releaseDate: '2017/11/03',
          updatedAt: '2022/10/11 21:39:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sm4/symbol.png',
            logo: 'https://images.pokemontcg.io/sm4/logo.png',
          },
        },
        number: '9',
        images: {
          small: 'https://images.pokemontcg.io/sm4/9.png',
          large: 'https://images.pokemontcg.io/sm4/9_hires.png',
        },
      },
      {
        id: 'xyp-XY62',
        name: 'Absol-EX',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Pokémon-EX rule: When a Pokémon-EX has been Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'xyp',
          name: 'XY Black Star Promos',
          series: 'XY',
          printedTotal: 211,
          total: 216,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PR-XY',
          releaseDate: '2013/10/12',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xyp/symbol.png',
            logo: 'https://images.pokemontcg.io/xyp/logo.png',
          },
        },
        number: 'XY62',
        images: {
          small: 'https://images.pokemontcg.io/xyp/XY62.png',
          large: 'https://images.pokemontcg.io/xyp/XY62_hires.png',
        },
      },
      {
        id: 'ex16-92',
        name: 'Absol ex',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'When Pokémon-ex has been Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'ex16',
          name: 'Power Keepers',
          series: 'EX',
          printedTotal: 108,
          total: 108,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'PK',
          releaseDate: '2007/02/02',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/ex16/symbol.png',
            logo: 'https://images.pokemontcg.io/ex16/logo.png',
          },
        },
        number: '92',
        images: {
          small: 'https://images.pokemontcg.io/ex16/92.png',
          large: 'https://images.pokemontcg.io/ex16/92_hires.png',
        },
      },
      {
        id: 'sv3-135',
        name: 'Absol ex',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'sv3',
          name: 'Obsidian Flames',
          series: 'Scarlet & Violet',
          printedTotal: 197,
          total: 230,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          releaseDate: '2023/08/11',
          updatedAt: '2023/08/11 15:00:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sv3/symbol.png',
            logo: 'https://images.pokemontcg.io/sv3/logo.png',
          },
        },
        number: '135',
        images: {
          small: 'https://images.pokemontcg.io/sv3/135.png',
          large: 'https://images.pokemontcg.io/sv3/135_hires.png',
        },
      },
      {
        id: 'pl3-1',
        name: 'Absol G',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'pl3',
          name: 'Supreme Victors',
          series: 'Platinum',
          printedTotal: 147,
          total: 153,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'SV',
          releaseDate: '2009/08/19',
          updatedAt: '2018/03/07 22:40:00',
          images: {
            symbol: 'https://images.pokemontcg.io/pl3/symbol.png',
            logo: 'https://images.pokemontcg.io/pl3/logo.png',
          },
        },
        number: '1',
        images: {
          small: 'https://images.pokemontcg.io/pl3/1.png',
          large: 'https://images.pokemontcg.io/pl3/1_hires.png',
        },
      },
      {
        id: 'pl3-141',
        name: 'Absol G LV.X',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Put this card onto your Active Absol G. Absol G LV.X can use any attack, Poké-Power, or Poké-Body from its previous level.',
        ],
        set: {
          id: 'pl3',
          name: 'Supreme Victors',
          series: 'Platinum',
          printedTotal: 147,
          total: 153,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'SV',
          releaseDate: '2009/08/19',
          updatedAt: '2018/03/07 22:40:00',
          images: {
            symbol: 'https://images.pokemontcg.io/pl3/symbol.png',
            logo: 'https://images.pokemontcg.io/pl3/logo.png',
          },
        },
        number: '141',
        images: {
          small: 'https://images.pokemontcg.io/pl3/141.png',
          large: 'https://images.pokemontcg.io/pl3/141_hires.png',
        },
      },
      {
        id: 'sv3-214',
        name: 'Absol ex',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'sv3',
          name: 'Obsidian Flames',
          series: 'Scarlet & Violet',
          printedTotal: 197,
          total: 230,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          releaseDate: '2023/08/11',
          updatedAt: '2023/08/11 15:00:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sv3/symbol.png',
            logo: 'https://images.pokemontcg.io/sv3/logo.png',
          },
        },
        number: '214',
        images: {
          small: 'https://images.pokemontcg.io/sv3/214.png',
          large: 'https://images.pokemontcg.io/sv3/214_hires.png',
        },
      },
      {
        id: 'swsh9tg-TG24',
        name: "Acerola's Premonition",
        supertype: 'Trainer',
        rules: [
          'Your opponent reveals their hand, and you draw a card for each Trainer card you find there.',
          'You may play only 1 Supporter card during your turn.',
        ],
        set: {
          id: 'swsh9tg',
          name: 'Brilliant Stars Trainer Gallery',
          series: 'Sword & Shield',
          printedTotal: 30,
          total: 30,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'BRS',
          releaseDate: '2022/02/25',
          updatedAt: '2022/02/23 09:45:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh9tg/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh9tg/logo.png',
          },
        },
        number: 'TG24',
        images: {
          small: 'https://images.pokemontcg.io/swsh9tg/TG24.png',
          large: 'https://images.pokemontcg.io/swsh9tg/TG24_hires.png',
        },
      },
      {
        id: 'swsh9-129',
        name: "Acerola's Premonition",
        supertype: 'Trainer',
        rules: [
          'Your opponent reveals their hand, and you draw a card for each Trainer card you find there.',
          'You may play only 1 Supporter card during your turn.',
        ],
        set: {
          id: 'swsh9',
          name: 'Brilliant Stars',
          series: 'Sword & Shield',
          printedTotal: 172,
          total: 186,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'BRS',
          releaseDate: '2022/02/25',
          updatedAt: '2022/02/23 09:45:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh9/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh9/logo.png',
          },
        },
        number: '129',
        images: {
          small: 'https://images.pokemontcg.io/swsh9/129.png',
          large: 'https://images.pokemontcg.io/swsh9/129_hires.png',
        },
      },
      {
        id: 'xy7-69',
        name: 'Ace Trainer',
        supertype: 'Trainer',
        rules: [
          'You can play this card only if you have more Prize cards left than your opponent.',
          'Each player shuffles his or her hand into his or her deck. Then, draw 6 cards. Your opponent draws 3 cards.',
          'You may play only 1 Supporter card during your turn (before your attack).',
        ],
        set: {
          id: 'xy7',
          name: 'Ancient Origins',
          series: 'XY',
          printedTotal: 98,
          total: 100,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'AOR',
          releaseDate: '2015/08/12',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xy7/symbol.png',
            logo: 'https://images.pokemontcg.io/xy7/logo.png',
          },
        },
        number: '69',
        images: {
          small: 'https://images.pokemontcg.io/xy7/69.png',
          large: 'https://images.pokemontcg.io/xy7/69_hires.png',
        },
      },
      {
        id: 'bw5-11',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'bw5',
          name: 'Dark Explorers',
          series: 'Black & White',
          printedTotal: 108,
          total: 111,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'DEX',
          releaseDate: '2012/05/09',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw5/symbol.png',
            logo: 'https://images.pokemontcg.io/bw5/logo.png',
          },
        },
        number: '11',
        images: {
          small: 'https://images.pokemontcg.io/bw5/11.png',
          large: 'https://images.pokemontcg.io/bw5/11_hires.png',
        },
      },
      {
        id: 'bw3-12',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'bw3',
          name: 'Noble Victories',
          series: 'Black & White',
          printedTotal: 101,
          total: 102,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'NVI',
          releaseDate: '2011/11/16',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw3/symbol.png',
            logo: 'https://images.pokemontcg.io/bw3/logo.png',
          },
        },
        number: '12',
        images: {
          small: 'https://images.pokemontcg.io/bw3/12.png',
          large: 'https://images.pokemontcg.io/bw3/12_hires.png',
        },
      },
      {
        id: 'swsh8-14',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'swsh8',
          name: 'Fusion Strike',
          series: 'Sword & Shield',
          printedTotal: 264,
          total: 284,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'FST',
          releaseDate: '2021/11/12',
          updatedAt: '2021/11/12 07:32:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh8/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh8/logo.png',
          },
        },
        number: '14',
        images: {
          small: 'https://images.pokemontcg.io/swsh8/14.png',
          large: 'https://images.pokemontcg.io/swsh8/14_hires.png',
        },
      },
    ],
    types: ['Grass', 'Water', 'Darkness', 'Psychic'],
    name: 'Test 1',
    trainers: 6,
    pokemons: 22,
  },
  {
    id: '1701217624256',
    cards: [
      {
        id: 'pl2-88',
        name: "Aaron's Collection",
        supertype: 'Trainer',
        rules: [
          'You can play only one Supporter card each turn. When you play this card, put it next to your Active Pokémon. When your turn ends, discard this card.',
          'Search your discard pile for up to 2 in any combination of Pokémon SP and basic Energy cards, show them to your opponent, and put them into your hand.',
        ],
        set: {
          id: 'pl2',
          name: 'Rising Rivals',
          series: 'Platinum',
          printedTotal: 111,
          total: 120,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'RR',
          releaseDate: '2009/05/16',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/pl2/symbol.png',
            logo: 'https://images.pokemontcg.io/pl2/logo.png',
          },
        },
        number: '88',
        images: {
          small: 'https://images.pokemontcg.io/pl2/88.png',
          large: 'https://images.pokemontcg.io/pl2/88_hires.png',
        },
      },
      {
        id: 'xy4-117',
        name: 'AZ',
        supertype: 'Trainer',
        rules: [
          'Put 1 Pokémon into your hand. (Discard all cards attached to that Pokémon.)',
          'You may play only 1 Supporter card during your turn (before your attack).',
        ],
        set: {
          id: 'xy4',
          name: 'Phantom Forces',
          series: 'XY',
          printedTotal: 119,
          total: 124,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PHF',
          releaseDate: '2014/11/05',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xy4/symbol.png',
            logo: 'https://images.pokemontcg.io/xy4/logo.png',
          },
        },
        number: '117',
        images: {
          small: 'https://images.pokemontcg.io/xy4/117.png',
          large: 'https://images.pokemontcg.io/xy4/117_hires.png',
        },
      },
      {
        id: 'xy4-91',
        name: 'AZ',
        supertype: 'Trainer',
        rules: [
          'Put 1 Pokémon into your hand. (Discard all cards attached to that Pokémon.)',
          'You may play only 1 Supporter card during your turn (before your attack).',
        ],
        set: {
          id: 'xy4',
          name: 'Phantom Forces',
          series: 'XY',
          printedTotal: 119,
          total: 124,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PHF',
          releaseDate: '2014/11/05',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xy4/symbol.png',
            logo: 'https://images.pokemontcg.io/xy4/logo.png',
          },
        },
        number: '91',
        images: {
          small: 'https://images.pokemontcg.io/xy4/91.png',
          large: 'https://images.pokemontcg.io/xy4/91_hires.png',
        },
      },
      {
        id: 'dp2-19',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'dp2',
          name: 'Mysterious Treasures',
          series: 'Diamond & Pearl',
          printedTotal: 123,
          total: 124,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'MT',
          releaseDate: '2007/08/01',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/dp2/symbol.png',
            logo: 'https://images.pokemontcg.io/dp2/logo.png',
          },
        },
        number: '19',
        images: {
          small: 'https://images.pokemontcg.io/dp2/19.png',
          large: 'https://images.pokemontcg.io/dp2/19_hires.png',
        },
      },
      {
        id: 'bw10-26',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Water'],
        set: {
          id: 'bw10',
          name: 'Plasma Blast',
          series: 'Black & White',
          printedTotal: 101,
          total: 105,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PLB',
          releaseDate: '2013/08/14',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw10/symbol.png',
            logo: 'https://images.pokemontcg.io/bw10/logo.png',
          },
        },
        number: '26',
        images: {
          small: 'https://images.pokemontcg.io/bw10/26.png',
          large: 'https://images.pokemontcg.io/bw10/26_hires.png',
        },
      },
      {
        id: 'sm11-42',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Water'],
        set: {
          id: 'sm11',
          name: 'Unified Minds',
          series: 'Sun & Moon',
          printedTotal: 236,
          total: 260,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'UNM',
          releaseDate: '2019/08/02',
          updatedAt: '2021/09/01 05:37:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sm11/symbol.png',
            logo: 'https://images.pokemontcg.io/sm11/logo.png',
          },
        },
        number: '42',
        images: {
          small: 'https://images.pokemontcg.io/sm11/42.png',
          large: 'https://images.pokemontcg.io/sm11/42_hires.png',
        },
      },
      {
        id: 'sm5-38',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Water'],
        set: {
          id: 'sm5',
          name: 'Ultra Prism',
          series: 'Sun & Moon',
          printedTotal: 156,
          total: 178,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'UPR',
          releaseDate: '2018/02/02',
          updatedAt: '2019/02/19 23:25:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sm5/symbol.png',
            logo: 'https://images.pokemontcg.io/sm5/logo.png',
          },
        },
        number: '38',
        images: {
          small: 'https://images.pokemontcg.io/sm5/38.png',
          large: 'https://images.pokemontcg.io/sm5/38_hires.png',
        },
      },
      {
        id: 'ex12-15',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'ex12',
          name: 'Legend Maker',
          series: 'EX',
          printedTotal: 92,
          total: 93,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'LM',
          releaseDate: '2006/02/01',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/ex12/symbol.png',
            logo: 'https://images.pokemontcg.io/ex12/logo.png',
          },
        },
        number: '15',
        images: {
          small: 'https://images.pokemontcg.io/ex12/15.png',
          large: 'https://images.pokemontcg.io/ex12/15_hires.png',
        },
      },
      {
        id: 'base5-49',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'base5',
          name: 'Team Rocket',
          series: 'Base',
          printedTotal: 82,
          total: 83,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'TR',
          releaseDate: '2000/04/24',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/base5/symbol.png',
            logo: 'https://images.pokemontcg.io/base5/logo.png',
          },
        },
        number: '49',
        images: {
          small: 'https://images.pokemontcg.io/base5/49.png',
          large: 'https://images.pokemontcg.io/base5/49_hires.png',
        },
      },
      {
        id: 'ecard1-93',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'ecard1',
          name: 'Expedition Base Set',
          series: 'E-Card',
          printedTotal: 165,
          total: 165,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'EX',
          releaseDate: '2002/09/15',
          updatedAt: '2022/10/10 15:12:00',
          images: {
            symbol: 'https://images.pokemontcg.io/ecard1/symbol.png',
            logo: 'https://images.pokemontcg.io/ecard1/logo.png',
          },
        },
        number: '93',
        images: {
          small: 'https://images.pokemontcg.io/ecard1/93.png',
          large: 'https://images.pokemontcg.io/ecard1/93_hires.png',
        },
      },
      {
        id: 'sv3pt5-63',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'sv3pt5',
          name: '151',
          series: 'Scarlet & Violet',
          printedTotal: 165,
          total: 207,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          releaseDate: '2023/09/22',
          updatedAt: '2023/09/22 15:00:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sv3pt5/symbol.png',
            logo: 'https://images.pokemontcg.io/sv3pt5/logo.png',
          },
        },
        number: '63',
        images: {
          small: 'https://images.pokemontcg.io/sv3pt5/63.png',
          large: 'https://images.pokemontcg.io/sv3pt5/63_hires.png',
        },
      },
      {
        id: 'dp2-69',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'dp2',
          name: 'Mysterious Treasures',
          series: 'Diamond & Pearl',
          printedTotal: 123,
          total: 124,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'MT',
          releaseDate: '2007/08/01',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/dp2/symbol.png',
            logo: 'https://images.pokemontcg.io/dp2/logo.png',
          },
        },
        number: '69',
        images: {
          small: 'https://images.pokemontcg.io/dp2/69.png',
          large: 'https://images.pokemontcg.io/dp2/69_hires.png',
        },
      },
      {
        id: 'xyp-XY178',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'xyp',
          name: 'XY Black Star Promos',
          series: 'XY',
          printedTotal: 211,
          total: 216,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PR-XY',
          releaseDate: '2013/10/12',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xyp/symbol.png',
            logo: 'https://images.pokemontcg.io/xyp/logo.png',
          },
        },
        number: 'XY178',
        images: {
          small: 'https://images.pokemontcg.io/xyp/XY178.png',
          large: 'https://images.pokemontcg.io/xyp/XY178_hires.png',
        },
      },
      {
        id: 'swsh35-38',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'swsh35',
          name: "Champion's Path",
          series: 'Sword & Shield',
          printedTotal: 73,
          total: 80,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'CPA',
          releaseDate: '2020/09/25',
          updatedAt: '2020/10/25 13:45:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh35/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh35/logo.png',
          },
        },
        number: '38',
        images: {
          small: 'https://images.pokemontcg.io/swsh35/38.png',
          large: 'https://images.pokemontcg.io/swsh35/38_hires.png',
        },
      },
      {
        id: 'bw9-67',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'bw9',
          name: 'Plasma Freeze',
          series: 'Black & White',
          printedTotal: 116,
          total: 122,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PLF',
          releaseDate: '2013/05/08',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw9/symbol.png',
            logo: 'https://images.pokemontcg.io/bw9/logo.png',
          },
        },
        number: '67',
        images: {
          small: 'https://images.pokemontcg.io/bw9/67.png',
          large: 'https://images.pokemontcg.io/bw9/67_hires.png',
        },
      },
      {
        id: 'sm4-9',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'sm4',
          name: 'Crimson Invasion',
          series: 'Sun & Moon',
          printedTotal: 111,
          total: 126,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'CIN',
          releaseDate: '2017/11/03',
          updatedAt: '2022/10/11 21:39:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sm4/symbol.png',
            logo: 'https://images.pokemontcg.io/sm4/logo.png',
          },
        },
        number: '9',
        images: {
          small: 'https://images.pokemontcg.io/sm4/9.png',
          large: 'https://images.pokemontcg.io/sm4/9_hires.png',
        },
      },
      {
        id: 'xyp-XY62',
        name: 'Absol-EX',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Pokémon-EX rule: When a Pokémon-EX has been Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'xyp',
          name: 'XY Black Star Promos',
          series: 'XY',
          printedTotal: 211,
          total: 216,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PR-XY',
          releaseDate: '2013/10/12',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xyp/symbol.png',
            logo: 'https://images.pokemontcg.io/xyp/logo.png',
          },
        },
        number: 'XY62',
        images: {
          small: 'https://images.pokemontcg.io/xyp/XY62.png',
          large: 'https://images.pokemontcg.io/xyp/XY62_hires.png',
        },
      },
      {
        id: 'ex16-92',
        name: 'Absol ex',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'When Pokémon-ex has been Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'ex16',
          name: 'Power Keepers',
          series: 'EX',
          printedTotal: 108,
          total: 108,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'PK',
          releaseDate: '2007/02/02',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/ex16/symbol.png',
            logo: 'https://images.pokemontcg.io/ex16/logo.png',
          },
        },
        number: '92',
        images: {
          small: 'https://images.pokemontcg.io/ex16/92.png',
          large: 'https://images.pokemontcg.io/ex16/92_hires.png',
        },
      },
      {
        id: 'sv3-135',
        name: 'Absol ex',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'sv3',
          name: 'Obsidian Flames',
          series: 'Scarlet & Violet',
          printedTotal: 197,
          total: 230,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          releaseDate: '2023/08/11',
          updatedAt: '2023/08/11 15:00:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sv3/symbol.png',
            logo: 'https://images.pokemontcg.io/sv3/logo.png',
          },
        },
        number: '135',
        images: {
          small: 'https://images.pokemontcg.io/sv3/135.png',
          large: 'https://images.pokemontcg.io/sv3/135_hires.png',
        },
      },
      {
        id: 'pl3-1',
        name: 'Absol G',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'pl3',
          name: 'Supreme Victors',
          series: 'Platinum',
          printedTotal: 147,
          total: 153,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'SV',
          releaseDate: '2009/08/19',
          updatedAt: '2018/03/07 22:40:00',
          images: {
            symbol: 'https://images.pokemontcg.io/pl3/symbol.png',
            logo: 'https://images.pokemontcg.io/pl3/logo.png',
          },
        },
        number: '1',
        images: {
          small: 'https://images.pokemontcg.io/pl3/1.png',
          large: 'https://images.pokemontcg.io/pl3/1_hires.png',
        },
      },
      {
        id: 'pl3-141',
        name: 'Absol G LV.X',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Put this card onto your Active Absol G. Absol G LV.X can use any attack, Poké-Power, or Poké-Body from its previous level.',
        ],
        set: {
          id: 'pl3',
          name: 'Supreme Victors',
          series: 'Platinum',
          printedTotal: 147,
          total: 153,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'SV',
          releaseDate: '2009/08/19',
          updatedAt: '2018/03/07 22:40:00',
          images: {
            symbol: 'https://images.pokemontcg.io/pl3/symbol.png',
            logo: 'https://images.pokemontcg.io/pl3/logo.png',
          },
        },
        number: '141',
        images: {
          small: 'https://images.pokemontcg.io/pl3/141.png',
          large: 'https://images.pokemontcg.io/pl3/141_hires.png',
        },
      },
      {
        id: 'sv3-214',
        name: 'Absol ex',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'sv3',
          name: 'Obsidian Flames',
          series: 'Scarlet & Violet',
          printedTotal: 197,
          total: 230,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          releaseDate: '2023/08/11',
          updatedAt: '2023/08/11 15:00:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sv3/symbol.png',
            logo: 'https://images.pokemontcg.io/sv3/logo.png',
          },
        },
        number: '214',
        images: {
          small: 'https://images.pokemontcg.io/sv3/214.png',
          large: 'https://images.pokemontcg.io/sv3/214_hires.png',
        },
      },
      {
        id: 'swsh9tg-TG24',
        name: "Acerola's Premonition",
        supertype: 'Trainer',
        rules: [
          'Your opponent reveals their hand, and you draw a card for each Trainer card you find there.',
          'You may play only 1 Supporter card during your turn.',
        ],
        set: {
          id: 'swsh9tg',
          name: 'Brilliant Stars Trainer Gallery',
          series: 'Sword & Shield',
          printedTotal: 30,
          total: 30,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'BRS',
          releaseDate: '2022/02/25',
          updatedAt: '2022/02/23 09:45:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh9tg/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh9tg/logo.png',
          },
        },
        number: 'TG24',
        images: {
          small: 'https://images.pokemontcg.io/swsh9tg/TG24.png',
          large: 'https://images.pokemontcg.io/swsh9tg/TG24_hires.png',
        },
      },
      {
        id: 'swsh9-129',
        name: "Acerola's Premonition",
        supertype: 'Trainer',
        rules: [
          'Your opponent reveals their hand, and you draw a card for each Trainer card you find there.',
          'You may play only 1 Supporter card during your turn.',
        ],
        set: {
          id: 'swsh9',
          name: 'Brilliant Stars',
          series: 'Sword & Shield',
          printedTotal: 172,
          total: 186,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'BRS',
          releaseDate: '2022/02/25',
          updatedAt: '2022/02/23 09:45:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh9/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh9/logo.png',
          },
        },
        number: '129',
        images: {
          small: 'https://images.pokemontcg.io/swsh9/129.png',
          large: 'https://images.pokemontcg.io/swsh9/129_hires.png',
        },
      },
      {
        id: 'xy7-69',
        name: 'Ace Trainer',
        supertype: 'Trainer',
        rules: [
          'You can play this card only if you have more Prize cards left than your opponent.',
          'Each player shuffles his or her hand into his or her deck. Then, draw 6 cards. Your opponent draws 3 cards.',
          'You may play only 1 Supporter card during your turn (before your attack).',
        ],
        set: {
          id: 'xy7',
          name: 'Ancient Origins',
          series: 'XY',
          printedTotal: 98,
          total: 100,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'AOR',
          releaseDate: '2015/08/12',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xy7/symbol.png',
            logo: 'https://images.pokemontcg.io/xy7/logo.png',
          },
        },
        number: '69',
        images: {
          small: 'https://images.pokemontcg.io/xy7/69.png',
          large: 'https://images.pokemontcg.io/xy7/69_hires.png',
        },
      },
      {
        id: 'bw5-11',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'bw5',
          name: 'Dark Explorers',
          series: 'Black & White',
          printedTotal: 108,
          total: 111,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'DEX',
          releaseDate: '2012/05/09',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw5/symbol.png',
            logo: 'https://images.pokemontcg.io/bw5/logo.png',
          },
        },
        number: '11',
        images: {
          small: 'https://images.pokemontcg.io/bw5/11.png',
          large: 'https://images.pokemontcg.io/bw5/11_hires.png',
        },
      },
      {
        id: 'bw3-12',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'bw3',
          name: 'Noble Victories',
          series: 'Black & White',
          printedTotal: 101,
          total: 102,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'NVI',
          releaseDate: '2011/11/16',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw3/symbol.png',
            logo: 'https://images.pokemontcg.io/bw3/logo.png',
          },
        },
        number: '12',
        images: {
          small: 'https://images.pokemontcg.io/bw3/12.png',
          large: 'https://images.pokemontcg.io/bw3/12_hires.png',
        },
      },
      {
        id: 'swsh8-14',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'swsh8',
          name: 'Fusion Strike',
          series: 'Sword & Shield',
          printedTotal: 264,
          total: 284,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'FST',
          releaseDate: '2021/11/12',
          updatedAt: '2021/11/12 07:32:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh8/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh8/logo.png',
          },
        },
        number: '14',
        images: {
          small: 'https://images.pokemontcg.io/swsh8/14.png',
          large: 'https://images.pokemontcg.io/swsh8/14_hires.png',
        },
      },
    ],
    types: ['Grass', 'Water', 'Darkness', 'Psychic'],
    name: 'Test 2',
    trainers: 6,
    pokemons: 22,
  },
  {
    id: '1701217624256',
    cards: [
      {
        id: 'pl2-88',
        name: "Aaron's Collection",
        supertype: 'Trainer',
        rules: [
          'You can play only one Supporter card each turn. When you play this card, put it next to your Active Pokémon. When your turn ends, discard this card.',
          'Search your discard pile for up to 2 in any combination of Pokémon SP and basic Energy cards, show them to your opponent, and put them into your hand.',
        ],
        set: {
          id: 'pl2',
          name: 'Rising Rivals',
          series: 'Platinum',
          printedTotal: 111,
          total: 120,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'RR',
          releaseDate: '2009/05/16',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/pl2/symbol.png',
            logo: 'https://images.pokemontcg.io/pl2/logo.png',
          },
        },
        number: '88',
        images: {
          small: 'https://images.pokemontcg.io/pl2/88.png',
          large: 'https://images.pokemontcg.io/pl2/88_hires.png',
        },
      },
      {
        id: 'xy4-117',
        name: 'AZ',
        supertype: 'Trainer',
        rules: [
          'Put 1 Pokémon into your hand. (Discard all cards attached to that Pokémon.)',
          'You may play only 1 Supporter card during your turn (before your attack).',
        ],
        set: {
          id: 'xy4',
          name: 'Phantom Forces',
          series: 'XY',
          printedTotal: 119,
          total: 124,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PHF',
          releaseDate: '2014/11/05',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xy4/symbol.png',
            logo: 'https://images.pokemontcg.io/xy4/logo.png',
          },
        },
        number: '117',
        images: {
          small: 'https://images.pokemontcg.io/xy4/117.png',
          large: 'https://images.pokemontcg.io/xy4/117_hires.png',
        },
      },
      {
        id: 'xy4-91',
        name: 'AZ',
        supertype: 'Trainer',
        rules: [
          'Put 1 Pokémon into your hand. (Discard all cards attached to that Pokémon.)',
          'You may play only 1 Supporter card during your turn (before your attack).',
        ],
        set: {
          id: 'xy4',
          name: 'Phantom Forces',
          series: 'XY',
          printedTotal: 119,
          total: 124,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PHF',
          releaseDate: '2014/11/05',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xy4/symbol.png',
            logo: 'https://images.pokemontcg.io/xy4/logo.png',
          },
        },
        number: '91',
        images: {
          small: 'https://images.pokemontcg.io/xy4/91.png',
          large: 'https://images.pokemontcg.io/xy4/91_hires.png',
        },
      },
      {
        id: 'dp2-19',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'dp2',
          name: 'Mysterious Treasures',
          series: 'Diamond & Pearl',
          printedTotal: 123,
          total: 124,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'MT',
          releaseDate: '2007/08/01',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/dp2/symbol.png',
            logo: 'https://images.pokemontcg.io/dp2/logo.png',
          },
        },
        number: '19',
        images: {
          small: 'https://images.pokemontcg.io/dp2/19.png',
          large: 'https://images.pokemontcg.io/dp2/19_hires.png',
        },
      },
      {
        id: 'bw10-26',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Water'],
        set: {
          id: 'bw10',
          name: 'Plasma Blast',
          series: 'Black & White',
          printedTotal: 101,
          total: 105,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PLB',
          releaseDate: '2013/08/14',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw10/symbol.png',
            logo: 'https://images.pokemontcg.io/bw10/logo.png',
          },
        },
        number: '26',
        images: {
          small: 'https://images.pokemontcg.io/bw10/26.png',
          large: 'https://images.pokemontcg.io/bw10/26_hires.png',
        },
      },
      {
        id: 'sm11-42',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Water'],
        set: {
          id: 'sm11',
          name: 'Unified Minds',
          series: 'Sun & Moon',
          printedTotal: 236,
          total: 260,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'UNM',
          releaseDate: '2019/08/02',
          updatedAt: '2021/09/01 05:37:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sm11/symbol.png',
            logo: 'https://images.pokemontcg.io/sm11/logo.png',
          },
        },
        number: '42',
        images: {
          small: 'https://images.pokemontcg.io/sm11/42.png',
          large: 'https://images.pokemontcg.io/sm11/42_hires.png',
        },
      },
      {
        id: 'sm5-38',
        name: 'Abomasnow',
        supertype: 'Pokémon',
        types: ['Water'],
        set: {
          id: 'sm5',
          name: 'Ultra Prism',
          series: 'Sun & Moon',
          printedTotal: 156,
          total: 178,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'UPR',
          releaseDate: '2018/02/02',
          updatedAt: '2019/02/19 23:25:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sm5/symbol.png',
            logo: 'https://images.pokemontcg.io/sm5/logo.png',
          },
        },
        number: '38',
        images: {
          small: 'https://images.pokemontcg.io/sm5/38.png',
          large: 'https://images.pokemontcg.io/sm5/38_hires.png',
        },
      },
      {
        id: 'ex12-15',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'ex12',
          name: 'Legend Maker',
          series: 'EX',
          printedTotal: 92,
          total: 93,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'LM',
          releaseDate: '2006/02/01',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/ex12/symbol.png',
            logo: 'https://images.pokemontcg.io/ex12/logo.png',
          },
        },
        number: '15',
        images: {
          small: 'https://images.pokemontcg.io/ex12/15.png',
          large: 'https://images.pokemontcg.io/ex12/15_hires.png',
        },
      },
      {
        id: 'base5-49',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'base5',
          name: 'Team Rocket',
          series: 'Base',
          printedTotal: 82,
          total: 83,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'TR',
          releaseDate: '2000/04/24',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/base5/symbol.png',
            logo: 'https://images.pokemontcg.io/base5/logo.png',
          },
        },
        number: '49',
        images: {
          small: 'https://images.pokemontcg.io/base5/49.png',
          large: 'https://images.pokemontcg.io/base5/49_hires.png',
        },
      },
      {
        id: 'ecard1-93',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'ecard1',
          name: 'Expedition Base Set',
          series: 'E-Card',
          printedTotal: 165,
          total: 165,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'EX',
          releaseDate: '2002/09/15',
          updatedAt: '2022/10/10 15:12:00',
          images: {
            symbol: 'https://images.pokemontcg.io/ecard1/symbol.png',
            logo: 'https://images.pokemontcg.io/ecard1/logo.png',
          },
        },
        number: '93',
        images: {
          small: 'https://images.pokemontcg.io/ecard1/93.png',
          large: 'https://images.pokemontcg.io/ecard1/93_hires.png',
        },
      },
      {
        id: 'sv3pt5-63',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'sv3pt5',
          name: '151',
          series: 'Scarlet & Violet',
          printedTotal: 165,
          total: 207,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          releaseDate: '2023/09/22',
          updatedAt: '2023/09/22 15:00:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sv3pt5/symbol.png',
            logo: 'https://images.pokemontcg.io/sv3pt5/logo.png',
          },
        },
        number: '63',
        images: {
          small: 'https://images.pokemontcg.io/sv3pt5/63.png',
          large: 'https://images.pokemontcg.io/sv3pt5/63_hires.png',
        },
      },
      {
        id: 'dp2-69',
        name: 'Abra',
        supertype: 'Pokémon',
        types: ['Psychic'],
        set: {
          id: 'dp2',
          name: 'Mysterious Treasures',
          series: 'Diamond & Pearl',
          printedTotal: 123,
          total: 124,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'MT',
          releaseDate: '2007/08/01',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/dp2/symbol.png',
            logo: 'https://images.pokemontcg.io/dp2/logo.png',
          },
        },
        number: '69',
        images: {
          small: 'https://images.pokemontcg.io/dp2/69.png',
          large: 'https://images.pokemontcg.io/dp2/69_hires.png',
        },
      },
      {
        id: 'xyp-XY178',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'xyp',
          name: 'XY Black Star Promos',
          series: 'XY',
          printedTotal: 211,
          total: 216,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PR-XY',
          releaseDate: '2013/10/12',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xyp/symbol.png',
            logo: 'https://images.pokemontcg.io/xyp/logo.png',
          },
        },
        number: 'XY178',
        images: {
          small: 'https://images.pokemontcg.io/xyp/XY178.png',
          large: 'https://images.pokemontcg.io/xyp/XY178_hires.png',
        },
      },
      {
        id: 'swsh35-38',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'swsh35',
          name: "Champion's Path",
          series: 'Sword & Shield',
          printedTotal: 73,
          total: 80,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'CPA',
          releaseDate: '2020/09/25',
          updatedAt: '2020/10/25 13:45:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh35/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh35/logo.png',
          },
        },
        number: '38',
        images: {
          small: 'https://images.pokemontcg.io/swsh35/38.png',
          large: 'https://images.pokemontcg.io/swsh35/38_hires.png',
        },
      },
      {
        id: 'bw9-67',
        name: 'Absol',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'bw9',
          name: 'Plasma Freeze',
          series: 'Black & White',
          printedTotal: 116,
          total: 122,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PLF',
          releaseDate: '2013/05/08',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw9/symbol.png',
            logo: 'https://images.pokemontcg.io/bw9/logo.png',
          },
        },
        number: '67',
        images: {
          small: 'https://images.pokemontcg.io/bw9/67.png',
          large: 'https://images.pokemontcg.io/bw9/67_hires.png',
        },
      },
      {
        id: 'sm4-9',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'sm4',
          name: 'Crimson Invasion',
          series: 'Sun & Moon',
          printedTotal: 111,
          total: 126,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'CIN',
          releaseDate: '2017/11/03',
          updatedAt: '2022/10/11 21:39:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sm4/symbol.png',
            logo: 'https://images.pokemontcg.io/sm4/logo.png',
          },
        },
        number: '9',
        images: {
          small: 'https://images.pokemontcg.io/sm4/9.png',
          large: 'https://images.pokemontcg.io/sm4/9_hires.png',
        },
      },
      {
        id: 'xyp-XY62',
        name: 'Absol-EX',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Pokémon-EX rule: When a Pokémon-EX has been Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'xyp',
          name: 'XY Black Star Promos',
          series: 'XY',
          printedTotal: 211,
          total: 216,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'PR-XY',
          releaseDate: '2013/10/12',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xyp/symbol.png',
            logo: 'https://images.pokemontcg.io/xyp/logo.png',
          },
        },
        number: 'XY62',
        images: {
          small: 'https://images.pokemontcg.io/xyp/XY62.png',
          large: 'https://images.pokemontcg.io/xyp/XY62_hires.png',
        },
      },
      {
        id: 'ex16-92',
        name: 'Absol ex',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'When Pokémon-ex has been Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'ex16',
          name: 'Power Keepers',
          series: 'EX',
          printedTotal: 108,
          total: 108,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'PK',
          releaseDate: '2007/02/02',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/ex16/symbol.png',
            logo: 'https://images.pokemontcg.io/ex16/logo.png',
          },
        },
        number: '92',
        images: {
          small: 'https://images.pokemontcg.io/ex16/92.png',
          large: 'https://images.pokemontcg.io/ex16/92_hires.png',
        },
      },
      {
        id: 'sv3-135',
        name: 'Absol ex',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'sv3',
          name: 'Obsidian Flames',
          series: 'Scarlet & Violet',
          printedTotal: 197,
          total: 230,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          releaseDate: '2023/08/11',
          updatedAt: '2023/08/11 15:00:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sv3/symbol.png',
            logo: 'https://images.pokemontcg.io/sv3/logo.png',
          },
        },
        number: '135',
        images: {
          small: 'https://images.pokemontcg.io/sv3/135.png',
          large: 'https://images.pokemontcg.io/sv3/135_hires.png',
        },
      },
      {
        id: 'pl3-1',
        name: 'Absol G',
        supertype: 'Pokémon',
        types: ['Darkness'],
        set: {
          id: 'pl3',
          name: 'Supreme Victors',
          series: 'Platinum',
          printedTotal: 147,
          total: 153,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'SV',
          releaseDate: '2009/08/19',
          updatedAt: '2018/03/07 22:40:00',
          images: {
            symbol: 'https://images.pokemontcg.io/pl3/symbol.png',
            logo: 'https://images.pokemontcg.io/pl3/logo.png',
          },
        },
        number: '1',
        images: {
          small: 'https://images.pokemontcg.io/pl3/1.png',
          large: 'https://images.pokemontcg.io/pl3/1_hires.png',
        },
      },
      {
        id: 'pl3-141',
        name: 'Absol G LV.X',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Put this card onto your Active Absol G. Absol G LV.X can use any attack, Poké-Power, or Poké-Body from its previous level.',
        ],
        set: {
          id: 'pl3',
          name: 'Supreme Victors',
          series: 'Platinum',
          printedTotal: 147,
          total: 153,
          legalities: {
            unlimited: 'Legal',
          },
          ptcgoCode: 'SV',
          releaseDate: '2009/08/19',
          updatedAt: '2018/03/07 22:40:00',
          images: {
            symbol: 'https://images.pokemontcg.io/pl3/symbol.png',
            logo: 'https://images.pokemontcg.io/pl3/logo.png',
          },
        },
        number: '141',
        images: {
          small: 'https://images.pokemontcg.io/pl3/141.png',
          large: 'https://images.pokemontcg.io/pl3/141_hires.png',
        },
      },
      {
        id: 'sv3-214',
        name: 'Absol ex',
        supertype: 'Pokémon',
        types: ['Darkness'],
        rules: [
          'Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.',
        ],
        set: {
          id: 'sv3',
          name: 'Obsidian Flames',
          series: 'Scarlet & Violet',
          printedTotal: 197,
          total: 230,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          releaseDate: '2023/08/11',
          updatedAt: '2023/08/11 15:00:00',
          images: {
            symbol: 'https://images.pokemontcg.io/sv3/symbol.png',
            logo: 'https://images.pokemontcg.io/sv3/logo.png',
          },
        },
        number: '214',
        images: {
          small: 'https://images.pokemontcg.io/sv3/214.png',
          large: 'https://images.pokemontcg.io/sv3/214_hires.png',
        },
      },
      {
        id: 'swsh9tg-TG24',
        name: "Acerola's Premonition",
        supertype: 'Trainer',
        rules: [
          'Your opponent reveals their hand, and you draw a card for each Trainer card you find there.',
          'You may play only 1 Supporter card during your turn.',
        ],
        set: {
          id: 'swsh9tg',
          name: 'Brilliant Stars Trainer Gallery',
          series: 'Sword & Shield',
          printedTotal: 30,
          total: 30,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'BRS',
          releaseDate: '2022/02/25',
          updatedAt: '2022/02/23 09:45:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh9tg/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh9tg/logo.png',
          },
        },
        number: 'TG24',
        images: {
          small: 'https://images.pokemontcg.io/swsh9tg/TG24.png',
          large: 'https://images.pokemontcg.io/swsh9tg/TG24_hires.png',
        },
      },
      {
        id: 'swsh9-129',
        name: "Acerola's Premonition",
        supertype: 'Trainer',
        rules: [
          'Your opponent reveals their hand, and you draw a card for each Trainer card you find there.',
          'You may play only 1 Supporter card during your turn.',
        ],
        set: {
          id: 'swsh9',
          name: 'Brilliant Stars',
          series: 'Sword & Shield',
          printedTotal: 172,
          total: 186,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'BRS',
          releaseDate: '2022/02/25',
          updatedAt: '2022/02/23 09:45:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh9/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh9/logo.png',
          },
        },
        number: '129',
        images: {
          small: 'https://images.pokemontcg.io/swsh9/129.png',
          large: 'https://images.pokemontcg.io/swsh9/129_hires.png',
        },
      },
      {
        id: 'xy7-69',
        name: 'Ace Trainer',
        supertype: 'Trainer',
        rules: [
          'You can play this card only if you have more Prize cards left than your opponent.',
          'Each player shuffles his or her hand into his or her deck. Then, draw 6 cards. Your opponent draws 3 cards.',
          'You may play only 1 Supporter card during your turn (before your attack).',
        ],
        set: {
          id: 'xy7',
          name: 'Ancient Origins',
          series: 'XY',
          printedTotal: 98,
          total: 100,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'AOR',
          releaseDate: '2015/08/12',
          updatedAt: '2020/08/14 09:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/xy7/symbol.png',
            logo: 'https://images.pokemontcg.io/xy7/logo.png',
          },
        },
        number: '69',
        images: {
          small: 'https://images.pokemontcg.io/xy7/69.png',
          large: 'https://images.pokemontcg.io/xy7/69_hires.png',
        },
      },
      {
        id: 'bw5-11',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'bw5',
          name: 'Dark Explorers',
          series: 'Black & White',
          printedTotal: 108,
          total: 111,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'DEX',
          releaseDate: '2012/05/09',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw5/symbol.png',
            logo: 'https://images.pokemontcg.io/bw5/logo.png',
          },
        },
        number: '11',
        images: {
          small: 'https://images.pokemontcg.io/bw5/11.png',
          large: 'https://images.pokemontcg.io/bw5/11_hires.png',
        },
      },
      {
        id: 'bw3-12',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'bw3',
          name: 'Noble Victories',
          series: 'Black & White',
          printedTotal: 101,
          total: 102,
          legalities: {
            unlimited: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'NVI',
          releaseDate: '2011/11/16',
          updatedAt: '2018/03/04 10:35:00',
          images: {
            symbol: 'https://images.pokemontcg.io/bw3/symbol.png',
            logo: 'https://images.pokemontcg.io/bw3/logo.png',
          },
        },
        number: '12',
        images: {
          small: 'https://images.pokemontcg.io/bw3/12.png',
          large: 'https://images.pokemontcg.io/bw3/12_hires.png',
        },
      },
      {
        id: 'swsh8-14',
        name: 'Accelgor',
        supertype: 'Pokémon',
        types: ['Grass'],
        set: {
          id: 'swsh8',
          name: 'Fusion Strike',
          series: 'Sword & Shield',
          printedTotal: 264,
          total: 284,
          legalities: {
            unlimited: 'Legal',
            standard: 'Legal',
            expanded: 'Legal',
          },
          ptcgoCode: 'FST',
          releaseDate: '2021/11/12',
          updatedAt: '2021/11/12 07:32:00',
          images: {
            symbol: 'https://images.pokemontcg.io/swsh8/symbol.png',
            logo: 'https://images.pokemontcg.io/swsh8/logo.png',
          },
        },
        number: '14',
        images: {
          small: 'https://images.pokemontcg.io/swsh8/14.png',
          large: 'https://images.pokemontcg.io/swsh8/14_hires.png',
        },
      },
    ],
    types: ['Grass', 'Water', 'Darkness', 'Psychic'],
    name: 'Test 3 de um nomebem maior que o comum',
    trainers: 6,
    pokemons: 22,
  },
] as any[];
